### ISSUE TITLE
C# Guid comparison bug

### ISSUE THREAD

**Issue by Leonhard-Benkert** [tomasbruckner/jest-dotnet#3]
Hello,
there is a bug when having Guids in the object that is going to be snapshoted. The creation of the snapshot succeedes and the tests come back positive, but the next time the tests are executed, the tests fail, because there is a "mismatch" in the Guid that is in the object and that of the snapshot, even though both are completely identical.
Sincerely,
L.B.

**Comment by tomasbruckner** [comment]
Hi @Leonhard-Benkert , thanks for reporting the issue!

Unfortunately, I was not able to reproduce this issue. Please take a look at this pull request where I have created a test suite for Guid.

Could you please provide me with a reproducible demo?

**Comment by tomasbruckner** [comment]
closing as stale and not reproducible
